### PR TITLE
fixes vue

### LINKED ISSUE #207: Deploying to CF Pages with a Vue Island is broken
### Astro Info

```block
Astro                    v4.5.12
Node                     v18.19.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/vue
                         @astrojs/tailwind
```

### Describe the Bug

Following this guide https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/ and then adding Vue and Tailwind I get this error when deploying the site (see attachment). Here's the repo https://github.com/kalepail/astro-vue-cf-app 

tl;dr error
```text
Error: Failed to publish your Function. Got error: Uncaught Error: No such module "@vue/server-renderer".
  imported from "renderers.mjs"
```

### What's the expected result?

The site should deploy successfully with the Vue Island

### Link to Minimal Reproducible Example

https://github.com/kalepail/astro-vue-cf-app

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
## Changes

- monkey patching until we have a decision in upstream
- upstream issue https://github.com/withastro/astro/pull/10601
- closes #207 

## Testing

- manually tested

## Docs

- bug fix, no docs needed

### CODE REVIEW

File: packages/cloudflare/src/index.ts [hunk 1]
```diff
@@ -173,7 +173,14 @@ export default function createIntegration(args?: Options): AstroIntegration {
...
 					vite.ssr.noExternal = true;
-					vite.ssr.external = _config.vite.ssr?.external ?? [];
+
+					if (typeof _config.vite.ssr?.external === 'undefined') vite.ssr.external = [];
+					if (typeof _config.vite.ssr?.external === 'boolean')
+						vite.ssr.external = _config.vite.ssr?.external;
+					if (Array.isArray(_config.vite.ssr?.external))
+						vite.ssr.external = _config.vite.ssr?.external.filter(
+							(entry) => entry !== '@vue/server-renderer'
+						);
```
Comment (ematipico) [inline packages/cloudflare/src/index.ts:183]: I suggest leaving a comment that explains why the server renderer of vite is placed inside `external`

**Review by ematipico — APPROVED** [review]

File: packages/cloudflare/src/index.ts (hunk 1 above)
Comment (alexanderniebuhr) [inline packages/cloudflare/src/index.ts:183]:
```suggestion
						// `@astrojs/vue` sets `@vue/server-renderer` to external
						// https://github.com/withastro/astro/blob/e648c5575a8774af739231cfa9fc27a32086aa5f/packages/integrations/vue/src/index.ts#L119
						// the cloudflare adapter needs to get all dependencies inlined, we use `noExternal` for that, but any `external` config overrides that
						// therefore we need to remove `@vue/server-renderer` from the external config again
						vite.ssr.external = _config.vite.ssr?.external.filter(
							(entry) => entry !== '@vue/server-renderer'
						);
```
