### PR TITLE
fix(cloudflare): duplicate patterns in `_routes.json`

### LINKED ISSUE #135: Astro Cloudflare - Failed to publish your Function. Got error: Error 8000057: Overlapping rules in `_routes.json` are not allowed.
### Astro Info

```block
Astro                    v4.2.1
Node                     v21.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @storyblok/astro
                         @astrojs/preact
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Hello, I'm developing an Astro website with static pages generated at the following paths:

- `/companies/index.astro`
- `/companies/[slug].astro`
- `/blog/index.astro`
- `/blog/[slug].astro`

Any other page is server-side rendered.

In order to avoid the `_routes.json` 100-entries limit error addressed in withastro/astro#6516, I'm manually excluding the static paths as described in the docs:

```js
adapter: cloudflare({
   routes: {
      exclude: ['/companies/*', '/blog/*'],
   },
})
```

The redundant paths `/companies/` and `/blog/` are not stripped away from the generated `_routes.json` if I have set the following redirect in `404.astro`:

```astro
---
return Astro.redirect('/', 301)
---
```

Causing the following deploy error (as `/companies/*` and `/blog/*` are also present in the `_routes.json` file):

```text
Error: Failed to publish your Function. Got error: Error 8000057: Overlapping rules in `_routes.json` are not allowed. Rule "/companies/" is overlapped by "/companies/*". Remove one of the rules to continue.
```

**Generated routes.json**

```json5
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    "/companies/",
    "/companies/*",
    "/blog/",
    "/blog/*",
    // ...
  ]
}
```

### What's the expected result?

```json5
{
  "version": 1,
  "include": [
    "/*"
  ],
  "exclude": [
    "/companies/*",
    "/blog/*",
    // ...
  ]
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cykvsk?file=dist%2F_routes.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

### LINKED ISSUE #136: explicit routes strategy overwritten by auto logic
### Describe the Bug

When explicitly setting a routes strategy it is not always used, depending on other checks. However those checks should only be used in the `auto` strategy

### What's the expected result?

Have all checks and protection for `auto` strategy, while allowing any custom strategy _(with no checks & protections)_ if set explicitly by `include` or `exclude` strategy

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
## Changes

- closes #135
- closes #136

### CODE REVIEW

**Comment by alexanderniebuhr** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #137** <a href="https://app.graphite.dev/github/pr/withastro/adapters/137?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/withastro/adapters/137?utm_source=stack-comment).

**Review by sarah11918 — APPROVED** [review]
Changeset made me laugh in the "this adapter sounds like an unruly pet" kind of way. *(This adapter barks at strangers and ignores commands...)*

Docs is happy with the changeset!

**Review by ematipico — APPROVED** [review]

File: packages/cloudflare/src/utils/deduplicatePatterns.ts [hunk 1]
```diff
@@ -10,16 +10,17 @@ export function deduplicatePatterns(patterns: string[]) {
...
 	// A value in the set may only occur once; it is unique in the set's collection.
 	// ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
+	const uniquePatterns = [...new Set(patterns)];
+	for (const pattern of uniquePatterns) {
+		if (pattern.endsWith('*')) {
+			openPatterns.push(new RegExp(`^${pattern.replace(/(\*\/)*\*$/g, '[^*\n]*$')}`));
+		}
+	}
+
 	return [...new Set(patterns)]
```
Comment (bluwy) [inline packages/cloudflare/src/utils/deduplicatePatterns.ts:20]: Could we also reuse `uniquePatterns` here?
```suggestion
	return uniquePatterns
```
